#!/usr/bin/env python3
"""Fix workflows:create and workflows:plan output paths."""

import os


def fix_file(filepath):
    """Apply fixes to a single file."""
    with open(filepath, "r") as f:
        content = f.read()

    original = content

    # Replace 1: workflows:create --mode tasks Output Contract
    old1 = "## --mode tasks (default)\n### Output Contract\n- Phases: Setup (1), Foundational (2, blocking), User Story phases (3+), Polish (final)\n- Format each task as: `[ID] [P?] [Story?] Description`"
    new1 = "## --mode tasks (default)\n### Output Contract\n- Write tasks.md to the same directory as the plan file\n- If plan is `docs/plans/YYYY-MM-DD-feature-plan.md`, write tasks to `docs/plans/YYYY-MM-DD-feature-tasks.md`\n- Do NOT create subdirectories; keep all artifacts flat in docs/plans/\n- Phases: Setup (1), Foundational (2, blocking), User Story phases (3+), Polish (final)\n- Format each task as: `[ID] [P?] [Story?] Description`"
    content = content.replace(old1, new1)

    # Replace 2: workflows:plan artifact path
    old2 = "- If additional artifacts are needed, declare intent under docs/plans/<plan-id>/ (spec.md, research.md, data-model.md, contracts/, quickstart.md, tasks.md, analysis.md, checklists/)."
    new2 = "- If additional artifacts are needed (tasks, analysis, checklists), write them as flat files alongside the plan: docs/plans/YYYY-MM-DD-feature-tasks.md"
    content = content.replace(old2, new2)

    # Replace 3: workflows:plan Artifact Plan section
    old3 = "## Artifact Plan (Optional Detail Directory)\n- Detail root: docs/plans/<plan-id>/\n- Optional artifacts: spec.md, research.md, data-model.md, contracts/, quickstart.md, tasks.md, analysis.md, checklists/"
    new3 = "## Artifact Plan (Optional)\n- Tasks file: docs/plans/YYYY-MM-DD-feature-tasks.md (generated by /ghostwire:workflows:create)\n- Analysis: docs/plans/YYYY-MM-DD-feature-analysis.md\n- Checklists: docs/plans/YYYY-MM-DD-feature-checklist-{domain}.md"
    content = content.replace(old3, new3)

    if content != original:
        with open(filepath, "w") as f:
            f.write(content)
        print(f"Fixed: {filepath}")
        return True
    return False


# Files to fix
files = [
    "src/execution/commands/commands-manifest.ts",
    "src/execution/commands/templates/workflows/plan.ts",
    ".github/prompts/workflows-plan.prompt.md",
    ".github/prompts/workflows-plan-2.prompt.md",
]

for f in files:
    if os.path.exists(f):
        fix_file(f)
    else:
        print(f"Skipping (not found): {f}")

print("Done!")
