import type { CommandDefinition } from "../claude-code-command-loader";

export type BuiltinCommandName =
  | "ghostwire:init-deep"
  | "ghostwire:ultrawork-loop"
  | "ghostwire:cancel-ultrawork"
  | "ghostwire:ulw-ultrawork"
  | "ghostwire:refactor"
  | "ghostwire:jack-in-work"
  | "ghostwire:stop-continuation"
  | "ghostwire:workflows:plan"
  | "ghostwire:workflows:create"
  | "ghostwire:workflows:status"
  | "ghostwire:workflows:complete"
  | "ghostwire:code:refactor"
  | "ghostwire:code:review"
  | "ghostwire:code:optimize"
  | "ghostwire:code:format"
  | "ghostwire:git:smart-commit"
  | "ghostwire:git:branch"
  | "ghostwire:git:merge"
  | "ghostwire:git:cleanup"
  | "ghostwire:project:init"
  | "ghostwire:project:build"
  | "ghostwire:project:deploy"
  | "ghostwire:project:test"
  | "ghostwire:util:clean"
  | "ghostwire:util:backup"
  | "ghostwire:util:restore"
  | "ghostwire:util:doctor"
  | "ghostwire:docs:deploy-docs"
  | "ghostwire:docs:release-docs"
  | "ghostwire:docs:feature-video"
  | "ghostwire:docs:test-browser"
  | "ghostwire:lint:ruby"
  // Plugin commands (non-workflow)
  | "ghostwire:plan-review"
  | "ghostwire:changelog"
  | "ghostwire:create-agent-skill"
  | "ghostwire:deepen-plan"
  | "ghostwire:deploy-docs"
  | "ghostwire:feature-video"
  | "ghostwire:generate-command"
  | "ghostwire:heal-skill"
  | "ghostwire:lfg"
  | "ghostwire:quiz-me"
  | "ghostwire:release-docs"
  | "ghostwire:report-bug"
  | "ghostwire:reproduce-bug"
  | "ghostwire:resolve-parallel"
  | "ghostwire:resolve-pr-parallel"
  | "ghostwire:resolve-todo-parallel"
  | "ghostwire:sync-tutorials"
  | "ghostwire:teach-me"
  | "ghostwire:test-browser"
  | "ghostwire:triage"
  | "ghostwire:xcode-test"
  // Plugin workflow commands
  | "ghostwire:workflows:brainstorm"
  | "ghostwire:workflows:learnings"
  | "ghostwire:workflows:review"
  | "ghostwire:workflows:work"
  // Spec commands (from specify integration)
  | "ghostwire:spec:create"
  | "ghostwire:spec:plan"
  | "ghostwire:spec:tasks"
  | "ghostwire:spec:implement"
  | "ghostwire:spec:clarify"
  | "ghostwire:spec:analyze"
  | "ghostwire:spec:checklist"
  | "ghostwire:spec:to-issues"
  // Project commands
  | "ghostwire:project:constitution";

export interface BuiltinCommandConfig {
  disabled_commands?: BuiltinCommandName[];
}

export type BuiltinCommands = Record<string, CommandDefinition>;
