import { loadMarkdownAgents } from "../agents/load-markdown-agents";
import { join, dirname } from "path";
import { writeFileSync } from "fs";

const AGENTS_DIR = join(dirname(import.meta.url.replace("file://", "")), "../agents/orchestration");
const OUTPUT_FILE = join(
  dirname(import.meta.url.replace("file://", "")),
  "../src/agents/agents-manifest.ts",
);

async function generateAgentsManifest() {
  const agents = await loadMarkdownAgents(AGENTS_DIR);
  return agents;
}

async function main() {
  const manifest = await generateAgentsManifest();

  // Generate TypeScript file - use JSON.stringify to safely handle all content
  const manifestJson = JSON.stringify(manifest, null, 2);

  const tsCode = `
// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by script/build-agents-manifest.ts
// Run 'bun run script/build-agents-manifest.ts' to regenerate

import type { LoadedAgent } from "../../agents/orchestration/load-markdown-agents";

export const AGENTS_MANIFEST: ReadonlyArray<LoadedAgent> = ${manifestJson} as const;

export function loadAgents(): Promise<LoadedAgent[]> {
  return Promise.resolve(AGENTS_MANIFEST as LoadedAgent[]);
}
`;

  writeFileSync(OUTPUT_FILE, tsCode);
  console.log(`Generated: ${OUTPUT_FILE}`);
  console.log(`Agents: ${manifest.length}`);
}

main().catch(console.error);
