import { SKILL_NAMES } from "../constants.js";

export const PLAN_AGENT_AVAILABLE_SKILLS = [
  SKILL_NAMES.GIT_MASTER,
  SKILL_NAMES.MAP_CODEBASE,
  SKILL_NAMES.PROJECT_SETUP,
  SKILL_NAMES.REVIEW,
];

export const DO_AGENT_AVAILABLE_SKILLS = [
  SKILL_NAMES.GIT_MASTER,
  SKILL_NAMES.REVIEW,
  SKILL_NAMES.PROJECT_INIT,
  SKILL_NAMES.BUILD,
  SKILL_NAMES.MAP_CODEBASE,
  SKILL_NAMES.PROJECT_SETUP,
];

export const CAPTURE_AGENT_AVAILABLE_SKILLS = [SKILL_NAMES.GIT_MASTER, SKILL_NAMES.CLOSE];

export const REVIEW_AGENT_AVAILABLE_SKILLS = [
  SKILL_NAMES.REVIEW,
  SKILL_NAMES.MAP_CODEBASE,
  SKILL_NAMES.GIT_MASTER,
];

export const ARCHITECT_AGENT_AVAILABLE_SKILLS = [
  SKILL_NAMES.REVIEW,
  SKILL_NAMES.MAP_CODEBASE,
];

export const DESIGNER_AGENT_AVAILABLE_SKILLS = [SKILL_NAMES.DESIGN, SKILL_NAMES.REVIEW];

export const GIT_AGENT_AVAILABLE_SKILLS = [SKILL_NAMES.GIT_MASTER];

export const SEARCH_AGENT_AVAILABLE_SKILLS = [
  SKILL_NAMES.GIT_MASTER,
  SKILL_NAMES.MAP_CODEBASE,
  SKILL_NAMES.PROJECT_SETUP,
];
