import type { SkillTemplate } from "../../../core/templates/types.js";
import { getSkillInstructions, getSkillReferences } from "../../.generated/templates.js";

export function getDesignSkillTemplate(): SkillTemplate {
  return {
    name: "spec-design",
    description:
      "Apply when designing, writing, reviewing, or modifying any frontend UI code. Combines implementation guidance with the Ponti Studios design system: strict tokens, accessibility, responsive layout, purposeful motion, and performance.",
    license: "MIT",
    compatibility: "Any frontend project using React (web or React Native)",
    metadata: {
      author: "Ponti Studios",
      version: "2.1",
      category: "Frontend",
      tags: [
        "frontend",
        "ui",
        "design-system",
        "design",
        "css",
        "html",
        "tokens",
        "gsap",
        "animation",
        "typography",
        "color",
        "spacing",
        "components",
        "accessibility",
        "performance",
        "responsive",
        "motion",
      ],
    },
    when: [
      "user is building or reviewing UI components",
      "user is writing or modifying a React component (web or React Native)",
      "user is adding or changing CSS or Tailwind classes",
      "user is adding or changing an animation or transition",
      "user is creating or referencing a design token",
      "user asks about component variants, states, spacing, color, or motion",
      "user asks about breakpoints, layout, grid, or responsive design",
      "user asks about accessibility, color contrast, or touch targets",
      "user asks about loading states, empty states, or error states",
      "user is implementing a form, input, or validation pattern",
      "user is implementing a modal, sheet, drawer, or overlay",
      "user is implementing a toast, notification, or alert",
      "UI code is being reviewed for correctness against the design system",
    ],
    applicability: [
      "Use when implementing frontend components, layouts, design systems, and interaction patterns",
      "Use when implementing any interactive animation — GSAP is mandatory on web",
      "Use when any color, spacing, radius, shadow, duration, or font value is referenced",
      "Use when specifying or reviewing component states (hover, focus, active, disabled, loading, error)",
      "Use when touch target size, icon sizing, or list virtualisation is relevant",
      "Use when implementing responsive layouts, breakpoint-dependent behaviour, or grid systems",
      "Use when writing placeholder text, error messages, or button labels (copy rules apply)",
      "Use when implementing overlay stacking, z-index, or focus trapping",
    ],
    termination: [
      "Component implemented with all required states and correct tokens",
      "Animation implemented using canonical GSAP sequences with reduced-motion guard",
      "Frontend UI is responsive and accessible across supported breakpoints",
      "Review complete with all checklist items verified",
      "Token added to token files if a value was missing",
    ],
    outputs: [
      "React component code (web or native) aligned to the design system",
      "Frontend layout and styling guidance",
      "GSAP animation using canonical sequences",
      "Token additions in the project token files if a value was missing",
      "Review checklist result with pass/fail for each rule",
    ],
    dependencies: [],
    references: getSkillReferences(
      "spec-design",
      "references/foundations.md",
      "references/motion.md",
      "references/components.md",
      "references/patterns.md",
      "references/chat.md",
    ),
    instructions: getSkillInstructions("spec-design"),
  };
}
