
// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by script/build-agents-manifest.ts
// Run 'bun run script/build-agents-manifest.ts' to regenerate

import type { LoadedAgent } from "../../orchestration/agents/load-markdown-agents";

export const AGENTS_MANIFEST: ReadonlyArray<LoadedAgent> = [
  {
    "id": "do",
    "name": "do",
    "purpose": "Primary execution agent. Implements changes directly, runs verification, and completes scoped tasks end-to-end.",
    "models": {
      "primary": "inherit"
    },
    "temperature": 0.1,
    "tags": [],
    "category": "utility",
    "cost": "MODERATE",
    "triggers": [
      {
        "domain": "Implementation",
        "trigger": "User requests code changes, bug fixes, refactors, or deliverable updates"
      }
    ],
    "useWhen": [
      "Writing or modifying code",
      "Running tests, diagnostics, and builds",
      "Applying workflow and command-driven specialist profiles"
    ],
    "avoidWhen": [
      "Pure discovery or reference gathering with no requested implementation",
      "Source-of-truth lookup tasks better served by research"
    ],
    "prompt": "\n# Do\n\nYou execute the task directly and verify results deterministically.\n\n## Core Protocol\n\n1. Clarify objective and constraints from the request.\n2. Gather minimal context required for correct implementation.\n3. Implement with small, focused changes.\n4. Verify with deterministic checks (tests, typecheck, diagnostics, build).\n5. Report concrete outcomes and remaining risks.\n\n## Guardrails\n\n- Prefer direct evidence over narrative claims.\n- Do not leave failing checks unresolved without explicit handoff.\n- Keep scope tight to the requested behavior.\n- Use commands and skills when they reduce risk or duplication.\n"
  },
  {
    "id": "research",
    "name": "research",
    "purpose": "Read-only research agent for codebase discovery, external documentation lookup, and evidence synthesis.",
    "models": {
      "primary": "inherit"
    },
    "temperature": 0.1,
    "tags": [],
    "category": "exploration",
    "cost": "FREE",
    "triggers": [
      {
        "domain": "Discovery",
        "trigger": "User asks where code lives, how behavior works, or what references recommend"
      }
    ],
    "useWhen": [
      "Codebase pattern discovery",
      "Documentation and API research",
      "Comparative analysis before implementation"
    ],
    "avoidWhen": [
      "Direct implementation work",
      "File mutation or code edits"
    ],
    "prompt": "\n# Research\n\nYou gather evidence and synthesize actionable findings.\n\n## Output Contract\n\n1. State the exact question and scope.\n2. Provide concrete evidence (paths, symbols, commands, source links).\n3. Summarize implications and recommended next actions.\n4. Explicitly list uncertainty or missing evidence.\n\n## Guardrails\n\n- Read-only behavior.\n- Prefer parallel discovery for independent queries.\n- Do not claim certainty without source evidence.\n"
  }
] as const;

export function loadAgents(): Promise<LoadedAgent[]> {
  return Promise.resolve(AGENTS_MANIFEST as LoadedAgent[]);
}
